config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'flights#index'

  resources :flights

  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id         :bigint           not null, primary key
#  city       :string
#  code       :string
#  country    :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Airport < ApplicationRecord
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  flight_id  :bigint           not null
#
# Indexes
#
#  index_bookings_on_flight_id  (flight_id)
#
# Foreign Keys
#
#  fk_rails_...  (flight_id => flights.id)
#
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id                   :bigint           not null, primary key
#  duration             :integer
#  scheduled_on         :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  arrival_airport_id   :bigint           not null
#  departure_airport_id :bigint           not null
#
# Indexes
#
#  index_flights_on_arrival_airport_id    (arrival_airport_id)
#  index_flights_on_departure_airport_id  (departure_airport_id)
#
# Foreign Keys
#
#  fk_rails_...  (arrival_airport_id => airports.id)
#  fk_rails_...  (departure_airport_id => airports.id)
#
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport'
  belongs_to :departure_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
  scope :upcoming, -> { where('scheduled_on >= ?', Date.today) }

  def formatted_date
    scheduled_on.strftime('%d-%m-%Y')
  end

  def formatted_time
    scheduled_on.strftime('%H:%M')
  end

  def formatted_duration
    hours = duration / 60
    minutes = duration % 60

    hours.zero? ? "#{minutes}min" : "#{hours}h #{minutes}min"
  end

  def self.search(search)
    flights = upcoming

    unless search.empty?
      flights = flights.where(departure_airport_id: search[:departure_airport_id],
                              arrival_airport_id: search[:arrival_airport_id])
    end

    unless search[:date].empty?
      formatted_date = Date.strptime(search[:date], '%Y-%m-%d').all_day
      flights = flights.where(scheduled_on: formatted_date)
    end

    flights.order(:scheduled_on)
  end
end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :bigint           not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  booking_id :bigint           not null
#
# Indexes
#
#  index_passengers_on_booking_id  (booking_id)
#
# Foreign Keys
#
#  fk_rails_...  (booking_id => bookings.id)
#
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    passenger_count = params[:passenger_count].to_i

    passenger_count.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      flash[:notice] = 'Please check your email for confiramtion information!'
      redirect_to @booking
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_search_options, only: [:index]

  def index
    return if search_params.empty?

    @filtered_flights = Flight.search(search_params)
  end

  private

  def set_search_options
    @search = params[:search]
    @airport_options = Airport.all.map { |airport| [airport.city, airport.id] }
    @default_date = Time.now.strftime('%d-%m-%Y')
  end

  def search_params
    params.permit(:departure_airport_id, :arrival_airport_id, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= form_with model: @booking, url: bookings_path, method: :post do |f|%>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  
  <h3>Passengers Details: </h3>
    <%= f.fields_for :passengers do |passenger_f| %>   
      <h4>Passenger nr: <%= passenger_f.options[:child_index] + 1 %></h4>
      <div style="display:flex;">
        <%= passenger_f.label :name %>
        <%= passenger_f.text_field :name, required: true %>

        <%= passenger_f.label :email %>
        <%= passenger_f.email_field :email, required: true, autocomplete: 'email' %>
      </div>
    <% end %>
    <%= f.submit "Book flight" %>
<% end %>

app/views/bookings/new.html.erb
<h1>Book a flight</h1>

<%= render 'flights/flight', flight: @flight %>

<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>Booking details</h1>

<%= render 'flights/flight', flight: @flight %>

<% @booking.passengers.each do |passenger| %>
  <h4>Ticket:</h4>
  <div style="display:flex;flex-direction:column;">
    <p><strong>Name: </strong> <%= passenger.name %></p>
    <p><strong>Email: </strong> <%= passenger.email %></p>
    <p><strong>From: </strong><%= @booking.flight.departure_airport.city %></p>
    <p><strong>To: </strong> <%= @booking.flight.arrival_airport.city %></p>
    <p><strong>Date: </strong><%= @booking.flight.formatted_date%></p>
    <p><strong>Time: </strong><%= @booking.flight.formatted_time%></p>
  </div>
<% end %>

app/views/flights/_available_flights.html.erb
<% if flights %>
  <% if flights.count.zero? %>
    <h4>There are no flights matching your search queries.</h4>
  <% else %>
    <h4><%= pluralize(flights.length, 'flight') %> matched your search</h4>

    <table>
      <thead>
        <tr>
          <th>Departs</th>
          <th>Arrives</th>
          <th>Date</th>
          <th>Departure</th>
          <th>Duration</th>
          <th>Passengers</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% flights.each do |flight| %>
          <tr>
            <td><%= flight.departure_airport.code %></td>
            <td><%= flight.arrival_airport.code %></td>
            <td><%= flight.formatted_date%></td>
            <td><%= flight.formatted_time%></td>
            <td><%= flight.formatted_duration %></td>
            <%= form_with url: new_booking_path, method: :get do |f| %>
              <%= f.hidden_field :flight_id, value: flight.id %>
              <td><%= f.select :passenger_count, options_for_select((1..4).each) %></td>
              <td><%= f.submit 'Book a flight' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/flights/_flight.html.erb
<table>
  <thead>
    <tr>
      <th>Departs</th>
      <th>Arrives</th>
      <th>Date</th>
      <th>Departure</th>
      <th>Duration</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= flight.departure_airport.city %></td>
      <td><%= flight.arrival_airport.city %></td>
      <td><%= flight.formatted_date %></td>
      <td><%= flight.formatted_time %></td>
      <td><%= flight.formatted_duration %></td>
    </tr>
  </tbody>
</table>

app/views/flights/_search_form.html.erb
<%= form_with(url: flights_path, method: :get, class: 'form') do |f| %>
    <%= f.select :departure_airport_id, 
                 options_for_select(@airport_options, params[:departure_airport_id]),
                 { prompt: "From"},
                 { required: true } %>

    <%= f.select :arrival_airport_id, 
                 options_for_select(@airport_options, params[:arrival_airport_id]), 
                 { prompt: "To"},
                 { required: true } %>
    
    <%= f.date_field :date, min: Date.today, value: params[:date] || @default_date  %>
  <%= f.submit "Search Flights" %>
<% end %>

app/views/flights/index.html.erb
<h3>Search for flights</h3>

<%= render 'search_form' %>

<br />

<%= render 'available_flights', flights: @filtered_flights %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>